import Head from "next/head";
import Link from "next/link";
import type { GetStaticPaths, GetStaticProps, InferGetStaticPropsType } from "next";
import { POSTS } from "../../src/data/seoContent";

type Post=typeof POSTS[number];
export const getStaticPaths:GetStaticPaths=async()=>({paths:POSTS.map(post=>({params:{slug:post.slug}})),fallback:false});
export const getStaticProps:GetStaticProps<{post:Post}>=async({params})=>{const post=POSTS.find(item=>item.slug===params?.slug);if(!post)return{notFound:true};return{props:{post}}};
export default function PostDetail({post}:InferGetStaticPropsType<typeof getStaticProps>){return <><Head><title>{post.title} | صمدی فارم</title><meta name="description" content={post.excerpt}/><meta property="og:title" content={post.title}/><meta property="og:description" content={post.excerpt}/><meta property="og:image" content={post.image}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Article",headline:post.title,description:post.excerpt,image:[post.image],datePublished:"2026-08-31",author:{"@type":"Organization",name:"صمدی فارم"}})}}/></Head><article className="post-detail shell"><nav className="breadcrumb" aria-label="مسیر صفحه"><Link href="/">خانه</Link><span>/</span><Link href="/posts">مقالات</Link><span>/</span><span>{post.title}</span></nav><header className="post-detail-head"><span>{post.category}</span><h1>{post.title}</h1><time>{post.date}</time><p>{post.excerpt}</p></header><div className="post-detail-image"><img src={post.image} alt={post.title}/></div><div className="post-content">{post.content.map((paragraph,i)=><p key={i}>{paragraph}</p>)}</div><footer className="seo-related"><Link href="/posts">← بازگشت به مجله</Link><Link href="/products">مشاهده محصولات ←</Link></footer></article></>}
