import type React from "react";
import Link from "next/link";
import { PRODUCTS, type CategoryId, type Product } from "../data/site";
import { formatToman, toFa } from "../hooks/useReveal";
import { IconBag, IconCheck, IconFlask, IconHex } from "./icons";
export type Filter = CategoryId | "all";
const FILTERS:{id:Filter;label:string}[]=[{id:"all",label:"همه‌ی محصولات"},{id:"single",label:"تک‌گل"},{id:"multi",label:"چندگیاه"},{id:"hive",label:"فرآورده‌های کندو"}];
const TAG_CLASS:Record<string,string>={honey:"",olive:"tag--olive",ember:"tag--ember"};
interface ProductsProps{filter:Filter;onFilter:(f:Filter)=>void;onAdd:(p:Product)=>void;justAddedId:string|null}
export default function Products({filter,onFilter,onAdd,justAddedId}:ProductsProps){const list=filter==="all"?PRODUCTS:PRODUCTS.filter(p=>p.cat===filter);return <section id="products" className="products-band"><div className="shell" style={{paddingTop:"2.5rem",paddingBottom:"4rem"}}><div className="catalog-toolbar"><div className="catalog-toolbar-title"><strong>فیلتر و انتخاب محصول</strong><span>{toFa(list.length)} محصول</span></div><div className="filters" role="tablist" aria-label="فیلتر دسته‌بندی محصولات">{FILTERS.map(f=><button key={f.id} type="button" role="tab" aria-selected={filter===f.id} className={`filter-chip${filter===f.id?" is-active":""}`} onClick={()=>onFilter(f.id)}>{f.label}</button>)}</div></div><div className="products-grid">{list.map((p,i)=><article key={p.id} className="product-card reveal" style={{"--d":`${(i%3)*.1}s`} as React.CSSProperties}><Link href={`/products/${p.id}`} className="product-media product-media-link" aria-label={`مشاهده جزئیات ${p.name}`}><img src={p.img} alt={p.name} loading="lazy"/>{p.tag&&<span className={`tag ${TAG_CLASS[p.tagTone??"honey"]}`}>{p.tag}</span>}</Link><div className="product-body"><div className="product-meta"><span className="weight"><IconHex size={12}/>{p.weight}</span><span>{toFa(FILTERS.find(f=>f.id===p.cat)?.label??"")}</span></div><h2 className="product-card-title"><Link href={`/products/${p.id}`}>{p.name}</Link></h2><p>{p.desc}</p><div className="product-foot"><div className="price">{formatToman(p.price)} <small>تومان</small></div><button type="button" className={`add-btn${justAddedId===p.id?" is-added":""}`} onClick={()=>onAdd(p)}>{justAddedId===p.id?<><IconCheck size={16}/>اضافه شد</>:<><IconBag size={16}/>افزودن</>}</button></div><Link href={`/products/${p.id}`} className="product-details-link">مشاهده مشخصات کامل و راهنمای خرید ←</Link></div></article>)}</div><p className="products-note reveal"><IconFlask size={17}/>هر شیشه همراه با برگه‌ی آزمایش معتبر — ساکارز زیر ۳٪ و رطوبت زیر ۱۸٪</p></div></section>}
