import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import type { CartEntry } from "../src/components/CartDrawer";
import { formatToman, toFa } from "../src/hooks/useReveal";
import { IconArrow, IconCheck, IconShield, IconWallet, IconX } from "../src/components/icons";
import type { ShippingAddress } from "./address";

interface CheckoutProps { cartEntries?: CartEntry[]; cartTotal?: number; onInc?: (id: string) => void; onDec?: (id: string) => void; onRemove?: (id: string) => void; }
type PaymentMethod = "zarinpal" | "crypto" | "card_to_card";
interface Gateways { methods: Record<PaymentMethod, boolean>; card_to_card: { card_number: string; card_holder_name: string }; }
interface CryptoInfo { network: string; wallet_address: string; }
const API_BASE = process.env.NEXT_PUBLIC_API_URL?.replace(/\/$/, "") || "http://localhost:8000";
const ADDRESS_KEY = "samadiFarm.shippingAddress";

export default function CheckoutPage({ cartEntries = [], cartTotal = 0, onInc, onDec, onRemove }: CheckoutProps) {
  const router = useRouter(); const [method, setMethod] = useState<PaymentMethod>("zarinpal"); const [gateways, setGateways] = useState<Gateways | null>(null); const [address, setAddress] = useState<ShippingAddress | null>(null); const [authenticated, setAuthenticated] = useState(false); const [checking, setChecking] = useState(true); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [crypto, setCrypto] = useState<CryptoInfo | null>(null); const [transactionHash, setTransactionHash] = useState(""); const [bankCode, setBankCode] = useState(""); const [reference, setReference] = useState("");
  const totalItems = useMemo(() => cartEntries.reduce((sum, item) => sum + item.qty, 0), [cartEntries]);
  const items = () => cartEntries.map(({ product, qty }) => ({ id: product.id, name: product.name, qty, price: product.price }));
  const enabled = gateways ? (Object.keys(gateways.methods) as PaymentMethod[]).filter((item) => gateways.methods[item]) : [];
  useEffect(() => { let mounted = true; (async () => { try { const [user, methods] = await Promise.all([fetch(`${API_BASE}/api/auth/me`, { credentials: "include" }), fetch(`${API_BASE}/api/payments/methods`)]); if (!mounted) return; setAuthenticated(user.ok); if (!methods.ok) throw new Error("دریافت روش‌های پرداخت ممکن نشد."); const data = await methods.json() as Gateways; setGateways(data); const first = (Object.keys(data.methods) as PaymentMethod[]).find((item) => data.methods[item]); if (first) setMethod(first); } catch (reason) { if (mounted) setError(reason instanceof Error ? reason.message : "ارتباط با سرور برقرار نشد."); } try { const saved = window.localStorage.getItem(ADDRESS_KEY); if (saved && mounted) setAddress(JSON.parse(saved)); } catch { /* no saved address */ } finally { if (mounted) setChecking(false); } })(); return () => { mounted = false; }; }, []);
  useEffect(() => { if (method !== "crypto") return; fetch(`${API_BASE}/api/payments/crypto/info`).then((r) => r.ok ? r.json() : Promise.reject()).then(setCrypto).catch(() => setError("اطلاعات پرداخت کریپتو دریافت نشد.")); }, [method]);
  const goLogin = () => router.push(`/login?next=${encodeURIComponent("/checkout")}`);
  const postReviewPayment = async (path: string, extra: Record<string, string>) => { const response = await fetch(`${API_BASE}${path}`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...extra, items: items(), shipping_address: address }) }); const data = await response.json().catch(() => ({})) as { detail?: string; order_reference?: string }; if (!response.ok) throw new Error(data.detail || "ثبت پرداخت انجام نشد."); setReference(data.order_reference || ""); };
  const pay = async () => { setError(""); setReference(""); if (!authenticated) return goLogin(); if (!address) return void router.push("/address"); setLoading(true); try { if (method === "card_to_card") { if (!bankCode.trim()) throw new Error("کد رهگیری بانکی را وارد کنید."); await postReviewPayment("/api/payments/card-to-card/transactions", { tracking_code: bankCode.trim() }); setBankCode(""); } else if (method === "crypto") { if (!transactionHash.trim()) throw new Error("هش تراکنش را وارد کنید."); await postReviewPayment("/api/payments/crypto/transactions", { currency: "USDT", transaction_hash: transactionHash.trim() }); setTransactionHash(""); } else { const response = await fetch(`${API_BASE}/api/payments/zarinpal/create`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items: items(), shipping_address: address }) }); const data = await response.json().catch(() => ({})) as { detail?: string; payment_url?: string }; if (!response.ok || !data.payment_url) throw new Error(data.detail || "اتصال به زرین‌پال انجام نشد."); window.location.href = data.payment_url; } } catch (reason) { setError(reason instanceof Error ? reason.message : "ثبت پرداخت انجام نشد."); } finally { setLoading(false); } };
  if (!cartEntries.length) return <section className="checkout-page"><div className="checkout-empty"><span className="checkout-empty-icon"><IconWallet size={34} /></span><h1>سبد خرید خالی است</h1><Link href="/products" className="btn btn-primary">مشاهده محصولات <IconArrow size={17} /></Link></div></section>;
  return <section className="checkout-page"><div className="checkout-head"><span className="eyebrow">پرداخت امن صمدی فارم</span><h1>تکمیل سفارش</h1><p>{checking ? "در حال بررسی حساب کاربری..." : "آدرس ارسال را بررسی کنید، سپس روش پرداخت را انتخاب کنید."}</p></div><div className="checkout-grid"><div className="checkout-main">
    {!authenticated && !checking ? <div className="checkout-card"><div className="address-required"><p>برای ادامه خرید وارد حساب کاربری شوید.</p><button className="btn btn-primary" onClick={goLogin}>ورود / ثبت‌نام <IconArrow size={17} /></button></div></div> : <div className="checkout-card"><div className="checkout-card-title"><span>۱</span><div><h2>آدرس ارسال</h2><p>اطلاعات گیرنده سفارش</p></div></div>{address ? <div className="shipping-address-card"><div className="shipping-address-main"><strong>{address.fullName}</strong><span>📞 {address.phone}</span><span>📍 {address.province}، {address.city}</span><span>{address.address}</span></div><button className="address-edit" onClick={() => router.push("/address")}>ویرایش آدرس</button></div> : <div className="address-required"><p>ابتدا آدرس ارسال را ثبت کنید.</p><button className="btn btn-primary" onClick={() => router.push("/address")}>ثبت آدرس</button></div>}</div>}
    {authenticated && <div className="checkout-card"><div className="checkout-card-title"><span>۲</span><div><h2>روش پرداخت</h2><p>فقط روش‌های فعال‌شده توسط مدیر نمایش داده می‌شوند.</p></div></div><div className="payment-methods">{gateways?.methods.zarinpal && <button className={`payment-method ${method === "zarinpal" ? "active" : ""}`} onClick={() => setMethod("zarinpal")}><span className="payment-logo zarinpal-logo">ZP</span><span><strong>زرین‌پال</strong><small>پرداخت آنلاین با کارت بانکی</small></span><span className="payment-radio" /></button>}{gateways?.methods.card_to_card && <button className={`payment-method ${method === "card_to_card" ? "active" : ""}`} onClick={() => setMethod("card_to_card")}><span className="payment-logo card-logo">کارت</span><span><strong>کارت به کارت</strong><small>واریز مستقیم و ثبت کد رهگیری بانکی</small></span><span className="payment-radio" /></button>}{gateways?.methods.crypto && <button className={`payment-method ${method === "crypto" ? "active" : ""}`} onClick={() => setMethod("crypto")}><span className="payment-logo crypto-logo">₿</span><span><strong>پرداخت با کریپتو</strong><small>ثبت هش تراکنش برای بررسی</small></span><span className="payment-radio" /></button>}</div>
      {enabled.length === 0 && <div className="payment-error"><IconX size={18} />هیچ روش پرداختی فعال نیست.</div>}{method === "card_to_card" && gateways && <div className="manual-payment-box"><p>مبلغ <strong>{formatToman(cartTotal)} تومان</strong> را به شماره کارت زیر واریز کنید و سپس کد رهگیری بانک را ثبت کنید.</p><label>شماره کارت مقصد</label><div className="payment-copy-row"><code dir="ltr">{gateways.card_to_card.card_number}</code><button onClick={() => navigator.clipboard.writeText(gateways.card_to_card.card_number)}>کپی</button></div>{gateways.card_to_card.card_holder_name && <small>به نام: {gateways.card_to_card.card_holder_name}</small>}<label htmlFor="bank-code">کد رهگیری بانکی</label><input id="bank-code" className="crypto-input" dir="ltr" value={bankCode} onChange={(e) => setBankCode(e.target.value)} placeholder="کد پیگیری واریز" /></div>}{method === "crypto" && <div className="crypto-wallet-box"><div><span>شبکه</span><strong>{crypto?.network || "در حال دریافت..."}</strong></div><label>آدرس کیف پول دریافت</label><div className="crypto-wallet-address"><code>{crypto?.wallet_address || "..."}</code></div><label htmlFor="transaction-hash">هش تراکنش</label><input id="transaction-hash" className="crypto-input" dir="ltr" value={transactionHash} onChange={(e) => setTransactionHash(e.target.value)} placeholder="0x..." /></div>}<div className="payment-notice"><IconShield size={19} /><span>اطلاعات پرداخت برای بررسی و پیگیری سفارش ثبت می‌شود.</span></div>{reference && <div className="profile-success">پرداخت برای بررسی ثبت شد. کد پیگیری سفارش شما: <strong dir="ltr">{reference}</strong> — در پنل کاربری هم قابل مشاهده است.</div>}{error && <div className="payment-error"><IconX size={18} />{error}</div>}<button className="btn btn-primary checkout-pay" onClick={pay} disabled={loading || !address || enabled.length === 0}>{loading ? "در حال ثبت..." : method === "zarinpal" ? `پرداخت ${formatToman(cartTotal)} تومان` : "ثبت پرداخت برای بررسی"}<IconArrow size={17} /></button></div>}
    <div className="checkout-card"><div className="checkout-card-title"><span>۳</span><div><h2>اقلام سفارش</h2><p>{toFa(totalItems)} قلم محصول</p></div></div><div className="checkout-items">{cartEntries.map(({ product, qty }) => <div className="checkout-item" key={product.id}><img src={product.img} alt={product.name} /><div className="checkout-item-info"><strong>{product.name}</strong><small>{product.weight} · {toFa(qty)} عدد</small></div><div className="checkout-item-actions"><button onClick={() => onInc?.(product.id)}>+</button><span>{toFa(qty)}</span><button onClick={() => onDec?.(product.id)}>−</button></div><strong>{formatToman(product.price * qty)} تومان</strong><button className="checkout-remove" onClick={() => onRemove?.(product.id)}><IconX size={15} /></button></div>)}</div></div>
  </div><aside className="checkout-summary"><div className="summary-top"><span>خلاصه سفارش</span><span>{toFa(totalItems)} قلم</span></div><div className="summary-lines"><div><span>مبلغ محصولات</span><strong>{formatToman(cartTotal)} تومان</strong></div></div><div className="summary-total"><span>مبلغ قابل پرداخت</span><strong>{formatToman(cartTotal)} <small>تومان</small></strong></div><div className="summary-security"><IconCheck size={17} /> پرداخت امن و پیگیری سفارش</div></aside></div></section>;
}
